name: Destroy

on:
  workflow_dispatch:
    inputs:
      aws_resource_identifier:
        description: Resource Identifier for deployed resources
  pull_request:
    types: [ closed ]

jobs:
  destroy:
    # if the branch name of the PR does not contain 'skip-deploy'
    if: "!contains(github.head_ref, 'skip-deploy')"
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.ref_name }}
      url: ${{ steps.deploy.outputs.vm_url }}
    steps:
    - id: destroy
      name: Destroy
      uses: bitovi/github-actions-deploy-docker-to-ec2@v0.5.2
      with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID_JIRA_INTEGRATIONS}}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY_JIRA_INTEGRATIONS}}
        aws_default_region: us-east-1

        stack_destroy: "true"
        #aws_resource_identifier: ${{ github.event.inputs.aws_resource_identifier }}

        # Provide a secret called `DOT_ENV` to append environment variables to the .env file
        dot_env: ${{ secrets.DOT_ENV }}

        domain_name: bitovi-jira.com
        app_port: 3000